export const svgList = {
  svg: true,
  rect: true,
  circle: true,
  ellipse: true,
  line: true,
  polyline: true,
  polygon: true,
  path: true,
  animate: true,
  animateColor: true,
  animateMotion: true,
  animateTransform: true,
  clipPath: true,
  "color-profile": true,
  "definition-src": true,
  defs: true,
  desc: true,
  filter: true,
  font: true,
  "font-face": true,
  "font-face-format": true,
  "font-face-name": true,
  "font-face-src": true,
  "font-face-uri": true,
  g: true,
  glyph: true,
  hkern: true,
  linearGradient: true,
  marker: true,
  mask: true,
  view: true,
} as any;


// t: true,
  // version: true,
  // d: true,
  // fill: true,
  // xmlns: true,
  // width: true,
  // height: true,
  // k: true,
  // k1: true,
  // k2: true,
  // k3: true,
  // k4: true,
  // offset: true,
  // opacity: true,
  // operator: true,
  // order: true,
  // origin: true,
  // overflow: true,
  // dx: true,
  // dy: true,
  // descent: true,
  // divisor: true,
  // cx: true,
  // cy: true,
  // clip: true,
  // "clip-path": true,
  // "clip-rule": true,
  // color: true,
  // bbox: true,
  // "fill-opacity": true,
  // "fill-rule": true,
  // filter: true,
  // filterRes: true,
  // "flood-color": true,
  // "flood-opacity": true,
  // "font-family": true,
  // "font-size": true,
  // "font-size-adjust": true,
  // "font-stretch": true,
  // "font-style": true,
  // "font-variant": true,
  // "font-weight": true,
  // g1: true,
  // g2: true,
  // "glpyh-name": true,
  // href: true,
  // mask: true,
  // min: true,
  // max: true,
  // mode: true,
  // path: true,
  // pathLength: true,
  // points: true,
  // pointsAtX: true,
  // pointsAtY: true,
  // pointsAtZ: true,
  // r: true,
  // radius: true,
  // rx: true,
  // ry: true,
  // rotate: true,
  // restart: true,
  // y: true,
  // x: true,
  // y1: true,
  // y2: true,
  // z: true,
  // "x-height": true,
  // x1: true,
  // x2: true,
  // "xlink:actuate": true,
  // "xlink:arcrole": true,
  // "xlink:href": true,
  // "xlink:role": true,
  // "xlink:show": true,
  // "xlink:type": true,
  // "xlink:title": true,
  // widths: true,
  // viewTarget: true,
  // u1: true,
  // u2: true,
  // stroke: true,
  // "stroke-opacity": true,
  // "stroke-width": true,
  // scale: true,
  // zoomAndPan: true,